name: OpenSuse mingw CI (docker image)

on:
  push:
    branches:
      - main
      - dev
      - features/*
      - feature/
  
jobs:

  docker_publish:
          
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: |
          docker/opensuse-mingw
        
    - name: Docker file push
      id: docker_push
      if: steps.changed-files.outputs.modified_files != ''
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jmkerloch/openfoam-opensuse-mingw
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker
        dockerfile: opensuse-mingw
        cache: true
        tags: opensuse-mingw

  build:

    runs-on: ubuntu-latest
    needs: docker_publish
    container: 'jmkerloch/openfoam-opensuse-mingw'

    steps:
    
    - uses: nelonoel/branch-name@v1.0.1
    
    - name: Checkout
      run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b ${BRANCH_NAME} .
          
    - name: Configure
      run: |
           source /etc-mingw/prefs.sh
           ./Allwmake -j

