name: OpenSuse mingw CI (docker image)

on:
  push:
    branches:
      - main
      - dev
      - features/*
      - feature/*
  
jobs:

  docker_publish:
          
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: |
          docker/opensuse-mingw
          
    - name: Log in to the Container registry
      if: steps.changed-files.outputs.modified_files != ''
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push to GitHub Packages
      if: steps.changed-files.outputs.modified_files != ''
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        tags: openfoam-opensuse-mingw
        dockerfile: docker/opensuse-mingw
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

  build:

    runs-on: ubuntu-latest
    needs: docker_publish
    container: 'ghcr.io/${{github.actor}}/porousmultiphasefoam:openfoam-opensuse-mingw'

    steps:
    
    - uses: nelonoel/branch-name@v1.0.1
    
    - name: Checkout
      run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b ${BRANCH_NAME} .
          
    - name: Build
      run: |
           FOAM_VERBOSE=true 
           source etc-mingw/prefs.sh
           source /openfoam/etc/bashrc           
           ls
           pwd
           ls /openfoam
           echo $FOAM_SETTINGS
           ./Allwmake -j
